### Classification

#### Types 
- binomial ---> 0,1 | True,False | yes,no
    - alogrithm we use is logistic regression
- multinomial ---> 0,1,2,3

### What we do 
- Here we take the threshold value whether the best fit line is above or below the given threshold value we can know.

- When an outlier value is present then best fit line will be deviated so in order to minizise the error in the linear regression ,so overcome this problem we use logistic regression.

### Logistic Regression

- To seperate the data correctly we need to choose best fit line perfectly.

- we use z = (sigma from i=1ton) yi * w^T * xi  ---> here w^T means weight in transpose
                            weight means the distane between the data value and the best fit line(hyper line).
- when we have our value more than 0 to 1 to reduce this effect then we use a sigmoid function
- sigmoid function y = 1/1+e^-z

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/Heart_disease.csv")

In [3]:
df.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [4]:
df['AHD'].unique()

array(['No', 'Yes'], dtype=object)

In [22]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          0
AHD           0
dtype: int64

In [23]:
df['Thal'].unique()

array(['fixed', 'normal', 'reversable'], dtype=object)

In [24]:
import numpy as np
### to replace nan with a value using numpy
df['Thal'].replace(np.nan,'fixed',inplace =True)

In [25]:
df['Ca'].replace(np.nan,0,inplace= True)

In [26]:
df['Ca'].unique()

array([0., 3., 2., 1.])

In [27]:
df['Thal'].unique()

array(['fixed', 'normal', 'reversable'], dtype=object)

In [28]:
df.drop('Unnamed: 0',axis =1,inplace =True)

In [29]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

In [30]:
## Label encoder

from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()
df['Thal'] = label.fit_transform(df['Thal'])

In [31]:
df['ChestPain'] = label.fit_transform(df['ChestPain'])
df['AHD'] = label.fit_transform(df['AHD'])

In [32]:
df.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1          3     145   233    1        2    150      0      2.3   
1   67    1          0     160   286    0        2    108      1      1.5   
2   67    1          0     120   229    0        2    129      1      2.6   
3   37    1          1     130   250    0        0    187      0      3.5   
4   41    0          2     130   204    0        2    172      0      1.4   

   Slope   Ca  Thal  AHD  
0      3  0.0     0    0  
1      2  3.0     1    1  
2      2  2.0     2    1  
3      3  0.0     1    0  
4      1  0.0     1    0

In [33]:
### select x and y

x = df.drop("AHD",axis =1)
y = df['AHD']

In [34]:
### Splitting the data

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =  0.3,random_state = 25)

In [35]:
### apply model

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\DILEEP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
model.predict([[63,1,3,145,233,1,2,150,0,2.3,3,0.0,0.0]])

array([0])

In [37]:
y_pred = model.predict(x_test)

In [38]:
### Evaluation metric is accuracy

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)*100


90.10989010989012

In [39]:
### to check whether values which is predicted correctly or not
## we use for that confusion_matrix 

confusion_matrix(y_test,y_pred)

array([[39,  5],
       [ 4, 43]], dtype=int64)

##### try to apply logistic regression to diabetes data and find accuracy and confusion matrix 

In [41]:
df = pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/diabetes.csv")

In [42]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [43]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [53]:
x = df[df.columns[:-1]]
y = df['Outcome']

In [55]:
y

0      1
1      0
2      1
3      0
4      1
5      0
6      1
7      0
8      1
9      1
10     0
11     1
12     0
13     1
14     1
15     1
16     1
17     1
18     0
19     1
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     0
28     0
29     0
      ..
738    0
739    1
740    1
741    0
742    0
743    1
744    0
745    0
746    1
747    0
748    1
749    1
750    1
751    0
752    0
753    1
754    1
755    1
756    0
757    1
758    0
759    1
760    0
761    1
762    0
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [56]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size = 0.3,random_state = 25)

In [57]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\DILEEP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [58]:
y_pred = model.predict(x_test)

In [62]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [63]:
accuracy_score(y_test,y_pred)*100

73.42007434944237

In [64]:
confusion_matrix(y_test,y_pred)

array([[302,  49],
       [ 94,  93]], dtype=int64)

balanced dataset ----> accuracy
inbalanced dataset ----> accuracy

Balanced
--------------
500
yes -- 400
no --- 100

inbalanced
-----------
- metrics we use
    - precision
    - recall