### Todays

- Data science life cycle
- Data science libraries

### Data science life cycle

Involves 6-7 steps 

- Business Understanding -> client's requirements
- Data Preparation -> collecting of data from database/client/traggle
- Data Munging / Data Wrangling -> convert huge data (raw) into user understanding format
    - feature selection
    - EDA Tool (Exclamatery Data analysis)
- Model Training -> with help of our aspects we train model(machine)
- Model Evalution -> we test the model weather it works properly or not
- Model Deployment -> submitting our model to client in different database tool
    - AWS
    - IBM waston studio
    - Microsoft azure
- Model Tracking -> tracking the model after deploying

## Data Analysis Libraries

- Numpy
- Pandas
- Matplotlib
- Seaborn
- Scipy

### Numpy

Numerical Python, developed in 2005 by Travis Oliphant
- used for creating arrays and it is 50 speeder than list

- arrays like :
            zero dimensional array
            single dimensional array
            Two dimensional array
            Multi dimensional array
            
- used for developing linear algebra, Fourier Transforms,Materics

In [1]:
import numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.16.4


### Creating arrays using numpy

- we use array methods to create array and length of arrays should be same for any dimensional

In [4]:
import numpy as np

x = np.array(23)
print(x)

23


In [5]:
### To know the dimension -> np.ndim(arrayvar)

np.ndim(x)

0

In [6]:
## 1-dimension
x1 = np.array([0,12,23,43])
print(x1)
print(np.ndim(x1))

[ 0 12 23 43]
1


In [10]:
## 2d-array
x2 = np.array([[1,2,3,4],[5,6,7,8]])
print(x2)
print(np.ndim(x2))

[[1 2 3 4]
 [5 6 7 8]]
2


In [11]:
## To get the number of elements -> inside the data is elements
# np.size(arrayvar)

np.size(x2)

8

In [12]:
## To get the no of rows and colums in array -> np.shape(arrayvar)
# output is (rows,cols)

np.shape(x2)

(2, 4)

In [14]:
### 3D-array  ---- [1d[2d[3d]]]

x3 = np.array([[[1,2,3],[4,5,7],[6,8,9]]])
print(x3)
print("Dimension ",np.ndim(x3))
print("No of elements:",np.size(x3))
print("no of rows and cols:",np.shape(x3))   # output --- (axis,dimension)

[[[1 2 3]
  [4 5 7]
  [6 8 9]]]
Dimension  3
No of elements: 9
no of rows and cols: (1, 3, 3)


In [15]:
### 3D-array  ---- [1d[2d[3d]]]

x3 = np.array([[[1,2,3],[4,5,7],[6,8,9],[0,11,12]]])
print(x3)
print("Dimension ",np.ndim(x3))
print("No of elements:",np.size(x3))
print("no of rows and cols:",np.shape(x3))   # output --- (axis,dimension)

[[[ 1  2  3]
  [ 4  5  7]
  [ 6  8  9]
  [ 0 11 12]]]
Dimension  3
No of elements: 12
no of rows and cols: (1, 4, 3)


### Methods to create arrays
- Zeros
- Ones
- linspace
- logspace
- arrange
- random


In [18]:
### Zeros -> np.zeros((rows,cols))

a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# to get elements in any type like int,str

a = np.zeros((2,3),dtype = int)
print(a)

[['' '' '']
 ['' '' '']]


In [22]:
### Ones -> np.ones((rows,cols))

a1 = np.ones((2,3),dtype = int)
print(a1)

[[1 1 1]
 [1 1 1]]


In [24]:
## to convert any dimension we can use ([]) for rows,cols
## (OR)  arrayvar.reshape(rows,cols)

a1 = np.ones(([2,3]),dtype = int)
print(a1)
print(np.ndim(a1))

[[1 1 1]
 [1 1 1]]
2


In [29]:
a1 = np.ones((2,3),dtype = int)
print(a1)
a2 = a1.reshape(2,3)
print(a2)

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


In [31]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [37]:
### To create an array we use np.arange(start,end,stepsize)
a = np.arange(1,12,2)
print(a)
print(np.ndim(a))

[ 1  3  5  7  9 11]
1


In [39]:
## Possibilities to reshape of 6 elements ---- (61,),(1,6),(2,3),
## (3,2)
a1 = a.reshape(2,3)
print(a)
print(a1)

[ 1  3  5  7  9 11]
[[ 1  3  5]
 [ 7  9 11]]


In [41]:
### logspace  -> np.logspace(start,end,stepsize)
l1 = np.logspace(1,5)
print(l1)

[1.00000000e+01 1.20679264e+01 1.45634848e+01 1.75751062e+01
 2.12095089e+01 2.55954792e+01 3.08884360e+01 3.72759372e+01
 4.49843267e+01 5.42867544e+01 6.55128557e+01 7.90604321e+01
 9.54095476e+01 1.15139540e+02 1.38949549e+02 1.67683294e+02
 2.02358965e+02 2.44205309e+02 2.94705170e+02 3.55648031e+02
 4.29193426e+02 5.17947468e+02 6.25055193e+02 7.54312006e+02
 9.10298178e+02 1.09854114e+03 1.32571137e+03 1.59985872e+03
 1.93069773e+03 2.32995181e+03 2.81176870e+03 3.39322177e+03
 4.09491506e+03 4.94171336e+03 5.96362332e+03 7.19685673e+03
 8.68511374e+03 1.04811313e+04 1.26485522e+04 1.52641797e+04
 1.84206997e+04 2.22299648e+04 2.68269580e+04 3.23745754e+04
 3.90693994e+04 4.71486636e+04 5.68986603e+04 6.86648845e+04
 8.28642773e+04 1.00000000e+05]


In [42]:
l1 = np.logspace(1,5,3)
print(l1)

[1.e+01 1.e+03 1.e+05]


In [43]:
## linspace -> np.linspace(start,end,stepsize)

l2 = np.linspace(1,4)
print(l2)

[1.         1.06122449 1.12244898 1.18367347 1.24489796 1.30612245
 1.36734694 1.42857143 1.48979592 1.55102041 1.6122449  1.67346939
 1.73469388 1.79591837 1.85714286 1.91836735 1.97959184 2.04081633
 2.10204082 2.16326531 2.2244898  2.28571429 2.34693878 2.40816327
 2.46938776 2.53061224 2.59183673 2.65306122 2.71428571 2.7755102
 2.83673469 2.89795918 2.95918367 3.02040816 3.08163265 3.14285714
 3.20408163 3.26530612 3.32653061 3.3877551  3.44897959 3.51020408
 3.57142857 3.63265306 3.69387755 3.75510204 3.81632653 3.87755102
 3.93877551 4.        ]


In [46]:
l2 = np.linspace(1,4,4)
print(l2)

[1. 2. 3. 4.]


In [48]:
l2 = np.linspace(1,4,6)
print(l2)

[1.  1.6 2.2 2.8 3.4 4. ]


In [51]:
### creating random numbers using numpy -> np.random.rand(row,col)

r = np.random.rand(2,4)
print(r)
r

[[0.61339347 0.03822681 0.19997083 0.5789351 ]
 [0.23348133 0.14625913 0.29979308 0.43193206]]


array([[0.61339347, 0.03822681, 0.19997083, 0.5789351 ],
       [0.23348133, 0.14625913, 0.29979308, 0.43193206]])

In [52]:
r = np.random.rand(2,4)
print(r)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [54]:
## we get randominteger from 0 to 1 using randint 
r1 = np.random.randint(2,100)
r1

6

In [55]:
## we get number from -0,-1 to +0,+1 using randn
r2 = np.random.randn(2,10)
r2

array([[-0.81002191, -0.52914912,  0.48567785,  0.02905141, -1.04819273,
        -1.503902  , -0.99872293, -1.39793481,  0.98454209, -1.11236101],
       [-0.06219863, -0.2721368 ,  0.53313436,  0.14474558,  1.68043614,
         0.02770976, -0.75347433, -1.79690776, -0.79867862,  0.65251686]])

In [56]:
np.ndim(r2)

2

In [57]:
### flatten() -> to convert multi dimension into single dimension

r3 = r2.flatten()
r3

array([-0.81002191, -0.52914912,  0.48567785,  0.02905141, -1.04819273,
       -1.503902  , -0.99872293, -1.39793481,  0.98454209, -1.11236101,
       -0.06219863, -0.2721368 ,  0.53313436,  0.14474558,  1.68043614,
        0.02770976, -0.75347433, -1.79690776, -0.79867862,  0.65251686])

In [58]:
np.ndim(r3)

1

### Accessing the elements in arrays
- indexing
    - +ve 
    - -ve
- slicing
    - [start : stop : stepsize]
- loop
     - for
     - while