### Numpy

In [1]:
import numpy as np

In [2]:
## to create array 1D
 
a = np.array(23)
print(a)

23


In [3]:
## to create array 2D

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
## to create array MultiD

c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
## To get dimension

print("dimension of b:",np.ndim(b))
print("dimension of c",c.ndim)

dimension of b: 2
dimension of c 3


In [6]:
### to get shape (rows and col)

print("shape of b ",np.shape(b))
print("shape od c ",c.shape)

shape of b  (2, 3)
shape od c  (1, 3, 3)


In [10]:
## To get type of element

b.dtype

### To change the type
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]],dtype = 'str')
print(c)
c.dtype

[[['1' '2' '3']
  ['4' '5' '6']
  ['7' '8' '9']]]


dtype('<U1')

In [22]:
### to get size (no of elements)

print("b elements ",b.size)
print("c elemets ",np.size(c))

b elements  6
c elemets  9


In [19]:
## To know the itemsize (byte size of element)

a.itemsize

4

In [23]:
## To get the no of byte for array 
b.nbytes

24

### Accessing / Changing Specific elements, rows, cols etc

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.ndim)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
2
(2, 7)


In [26]:
### to get specific element from array -> var[row,col]

print(a[1,4])

12


In [29]:
## like list

print(a[1,-3])

12


In [30]:
### To get specific row

print(a[0,:])

[1 2 3 4 5 6 7]


In [35]:
 ### to get specific col
    
print(a[:,1])

[2 9]


In [33]:
## To get the more row,col in specific  -> [start,end,stepsize]

print(a[0, 1:-1:2])

[2 4 6]


In [34]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [36]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [38]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [3]:
import numpy as np
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [4]:
b[0:,]

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [5]:
b[0:,0:,]

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [6]:
b[0:,1]

array([[3, 4]])

In [7]:
b[0:,1:,]

array([[[3, 4],
        [5, 6],
        [7, 8]]])

In [8]:
b[0:,0:,0]

array([[1, 3, 5, 7]])

In [10]:
b[0:,0:,1]

array([[2, 4, 6, 8]])

In [11]:
b[0,1,1]

4

In [16]:
b[:,1:,] = [[9,9],[8,8]]

ValueError: could not broadcast input array from shape (2,2) into shape (1,3,2)

In [14]:
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

### Intializing Different types of array

In [18]:
# all 0's matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# all 1's matrix
np.ones((4,2,2),dtype = 'int')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [20]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [24]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [25]:
# any other number( full_like)
np.full_like(c,4)

array([[[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]])

In [26]:
np.full(c.shape,6)

array([[[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]])

In [27]:
np.full_like((2,3),3)

array([3, 3])

In [28]:
np.random.rand(4,2)

array([[0.53162698, 0.39949923],
       [0.02955257, 0.80648201],
       [0.39924483, 0.5015533 ],
       [0.40966546, 0.36079705]])

In [29]:
np.random.random_sample(c.shape)

array([[[0.94949212, 0.93319212, 0.21341966],
        [0.63713065, 0.38476027, 0.93380938],
        [0.80871783, 0.05641212, 0.15037009]]])

In [31]:
np.random.randint(4, size = (3,3))

array([[3, 3, 2],
       [2, 0, 2],
       [2, 1, 3]])

In [33]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
arr = np.array([1,2,4,5])
r = np.repeat(c,3,axis = 1)
print(r)

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]
  [4 5 6]
  [7 8 9]
  [7 8 9]
  [7 8 9]]]


In [1]:
import numpy as np

In [10]:
###  Printing the matrix in required form

print("getting only ones")
one = np.ones((5,5))
print(out)
print("getting only zeros")
zero = np.zeros((3,3))
print(zero)
print("replacing the element")
zero[1,1] = 9
print(zero)
print("getting the required form of matrix")
one[1:4,1:4] = zero
print(one)

getting only ones
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
getting only zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
replacing the element
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
getting the required form of matrix
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying arrays

In [11]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
b = a  # copying array
b

array([1, 2, 3])

In [13]:
b[0] = 10    # changing the element
b 

array([10,  2,  3])

In [14]:
a    # main also changed

array([10,  2,  3])

In [15]:
b=a.copy()
b

array([10,  2,  3])

In [18]:
b[1] = 20
b


array([10, 20,  3])

In [19]:
print(a)

[10  2  3]


### Mathematics

In [20]:
a = np.array([1,2,4])
a

array([1, 2, 4])

In [21]:
a + 2

array([3, 4, 6])

In [22]:
a -2

array([-1,  0,  2])

In [23]:
a * 2

array([2, 4, 8])

In [24]:
a / 2

array([0.5, 1. , 2. ])

In [26]:
b = np.array([1,0,1])
a + b

array([2, 2, 5])

In [27]:
a ** 2

array([ 1,  4, 16], dtype=int32)

In [28]:
### sin
np.sin(a)

array([ 0.84147098,  0.90929743, -0.7568025 ])

In [29]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.65364362])

 ### Linear Algebra
 
 

In [30]:
a = np.ones((2,3))

In [33]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [34]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [35]:
## to get determinant
c  = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [36]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.min(stats, axis =0)

array([1, 2, 3])

In [38]:
np.min(stats)

1

In [39]:
np.max(stats, axis =1)

array([3, 6])

In [40]:
np.sum(stats)

21

In [41]:
np.sum(stats,axis =1)

array([ 6, 15])

### Reorganizing arrays

In [42]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

[[1 2 3]
 [4 5 6]]


In [45]:
print(before.shape)

(2, 3)


In [47]:
after = before.reshape((6,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [53]:
after = before.reshape((2,3))
print(after)

[[1 2 3]
 [4 5 6]]


In [55]:
### vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
### Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### miscellaneous

#### Load data from file

In [59]:
np.genfromtxt('x.npy',delimiter = ',')

ValueError: Some errors were detected !
    Line #2 (got 1 columns instead of 5)
    Line #3 (got 1 columns instead of 5)

In [61]:
### WE can index with a list  -> to get required values in array 
#we can use index number simply var[[index]]

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]   # index value in [[]]

array([2, 3, 9])

In [62]:
### Getting the matrix from 1 - 30 numbers

a = np.arange(1,31)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [85]:
b = a.reshape(6,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [83]:
# indexing the values of 11,12,16,17 matrix
print(a[2:4, 0:2])

IndexError: too many indices for array

In [86]:
# indexing the values of 11,12,16,17 matrix
b[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [89]:
#  get the diagonal form of row 1

print(b.diagonal(1))

[ 2  8 14 20]


In [90]:
print(b[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [95]:
#  indexing of top (4,5) and bottom(24,25,29,30)

print(b[0::-2])

[[1 2 3 4 5]]


In [96]:
print(b[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]
